version: '3'

services: 
    auth:
        build: 
            dockerfile: auth/Dockerfile
            context: ./
        ports: 
            - "${AUTH_SVC_PORT}:8081"
        volumes: 
            - ./auth:/usr/src/app
        networks:
            - sc_webcomposer

    client:
        build: 
            dockerfile: client/Dockerfile
            context: ./
        ports: 
            - "${CLIENT_SVC_PORT}:3000"
        volumes: 
            - ./client:/usr/src/app
        networks:
            - sc_webcomposer
        environment: 
            - CHOKIDAR_USEPOLLING=true

networks:
    sc_webcomposer:
        driver: bridge 